const ROLES = Object.freeze({
  TEACHER: 'TEACHER',
  ASSISTANT: 'ASSISTANT',
  STUDENT: 'STUDENT',
});

const ACCOUNT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  DISABLED: 'DISABLED',
});

const PERMISSIONS = Object.freeze({
  VIEW_STUDENTS: 'VIEW_STUDENTS',
  MANAGE_STUDENT_APPROVAL: 'MANAGE_STUDENT_APPROVAL',
  VIEW_STUDENT_ACTIVITY: 'VIEW_STUDENT_ACTIVITY',
  UPLOAD_MATERIALS: 'UPLOAD_MATERIALS',
  UPLOAD_VIDEOS: 'UPLOAD_VIDEOS',
  MANAGE_CONTENT: 'MANAGE_CONTENT',
  CREATE_QUIZZES: 'CREATE_QUIZZES',
  CREATE_EXAMS: 'CREATE_EXAMS',
  REVIEW_RESULTS: 'REVIEW_RESULTS',
  MANAGE_MEETINGS: 'MANAGE_MEETINGS',
  VIEW_ATTENDANCE: 'VIEW_ATTENDANCE',
  MANAGE_ANNOUNCEMENTS: 'MANAGE_ANNOUNCEMENTS',
});

const PERMISSION_LIST = Object.values(PERMISSIONS);

const PERMISSION_LABELS = Object.freeze({
  VIEW_STUDENTS: 'View students',
  MANAGE_STUDENT_APPROVAL: 'Approve / reject student registrations',
  VIEW_STUDENT_ACTIVITY: 'View student activity',
  UPLOAD_MATERIALS: 'Upload materials',
  UPLOAD_VIDEOS: 'Add lesson videos',
  MANAGE_CONTENT: 'Create and edit modules and lessons',
  CREATE_QUIZZES: 'Create quizzes',
  CREATE_EXAMS: 'Create exams',
  REVIEW_RESULTS: 'Review student results',
  MANAGE_MEETINGS: 'Manage live meetings',
  VIEW_ATTENDANCE: 'View attendance',
  MANAGE_ANNOUNCEMENTS: 'Manage announcements',
});

const ACTIVITY_TYPES = Object.freeze({
  LOGGED_IN: 'LOGGED_IN',
  MODULE_OPENED: 'MODULE_OPENED',
  LESSON_OPENED: 'LESSON_OPENED',
  VIDEO_STARTED: 'VIDEO_STARTED',
  VIDEO_PROGRESS: 'VIDEO_PROGRESS',
  VIDEO_COMPLETED: 'VIDEO_COMPLETED',
  MATERIAL_OPENED: 'MATERIAL_OPENED',
  QUIZ_STARTED: 'QUIZ_STARTED',
  QUIZ_COMPLETED: 'QUIZ_COMPLETED',
  EXAM_STARTED: 'EXAM_STARTED',
  EXAM_COMPLETED: 'EXAM_COMPLETED',
  LIVE_MEETING_JOINED: 'LIVE_MEETING_JOINED',
  LIVE_MEETING_LEFT: 'LIVE_MEETING_LEFT',
});

const ACTIVITY_TYPE_LIST = Object.values(ACTIVITY_TYPES);

const ENGAGEMENT = Object.freeze({
  ACTIVE: 'ACTIVE',
  AT_RISK: 'AT_RISK',
  INACTIVE: 'INACTIVE',
});

const MEETING_STATUS = Object.freeze({
  UPCOMING: 'UPCOMING',
  LIVE: 'LIVE',
  ENDED: 'ENDED',
  CANCELLED: 'CANCELLED',
});

const ATTENDANCE_STATUS = Object.freeze({
  INVITED: 'INVITED',
  JOINED: 'JOINED',
  ATTENDED: 'ATTENDED',
  ABSENT: 'ABSENT',
});

const QUESTION_TYPES = Object.freeze({
  MCQ: 'MCQ',
  TRUE_FALSE: 'TRUE_FALSE',
  SHORT_ANSWER: 'SHORT_ANSWER',
});

const MEETING_PROVIDERS = Object.freeze({
  ZOOM: 'ZOOM',
  TEAMS: 'TEAMS',
  SKYPE: 'SKYPE',
  GOOGLE_MEET: 'GOOGLE_MEET',
  OTHER: 'OTHER',
});

const NOTIFICATION_TYPES = Object.freeze({
  NEW_LESSON: 'NEW_LESSON',
  NEW_VIDEO: 'NEW_VIDEO',
  NEW_MATERIAL: 'NEW_MATERIAL',
  NEW_QUIZ: 'NEW_QUIZ',
  NEW_EXAM: 'NEW_EXAM',
  NEW_MEETING: 'NEW_MEETING',
  MEETING_SOON: 'MEETING_SOON',
  MEETING_LIVE: 'MEETING_LIVE',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  ACCOUNT_APPROVED: 'ACCOUNT_APPROVED',
  ACCOUNT_REJECTED: 'ACCOUNT_REJECTED',
  NEW_REGISTRATION: 'NEW_REGISTRATION',
  QUIZ_COMPLETED: 'QUIZ_COMPLETED',
  EXAM_COMPLETED: 'EXAM_COMPLETED',
  ATTENDANCE_UPDATE: 'ATTENDANCE_UPDATE',
});

// How early a student may enter a scheduled class.
const MEETING_JOIN_WINDOW_MINUTES = 10;

// A student counts as having attended once they stay this share of the meeting window.
const ATTENDANCE_MIN_RATIO = 0.3;
// Absolute floor in minutes so very long meetings do not require an unreasonable stay.
const ATTENDANCE_MIN_MINUTES = 5;

module.exports = {
  ROLES,
  ACCOUNT_STATUS,
  PERMISSIONS,
  PERMISSION_LIST,
  PERMISSION_LABELS,
  ACTIVITY_TYPES,
  ACTIVITY_TYPE_LIST,
  ENGAGEMENT,
  MEETING_STATUS,
  ATTENDANCE_STATUS,
  QUESTION_TYPES,
  MEETING_PROVIDERS,
  NOTIFICATION_TYPES,
  MEETING_JOIN_WINDOW_MINUTES,
  ATTENDANCE_MIN_RATIO,
  ATTENDANCE_MIN_MINUTES,
};
