module.exports = {
  User: require('./User'),
  Group: require('./Group'),
  Module: require('./Module'),
  Lesson: require('./Lesson'),
  Video: require('./Video'),
  Material: require('./Material'),
  Quiz: require('./Quiz'),
  QuizAttempt: require('./QuizAttempt'),
  Exam: require('./Exam'),
  ExamAttempt: require('./ExamAttempt'),
  VideoProgress: require('./VideoProgress'),
  MaterialAccess: require('./MaterialAccess'),
  StudentActivity: require('./StudentActivity'),
  LiveMeeting: require('./LiveMeeting'),
  MeetingAttendance: require('./MeetingAttendance'),
  Notification: require('./Notification'),
  Announcement: require('./Announcement'),
};
